# Generated by Django 4.1.4 on 2022-12-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DevStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(blank=True, upload_to="")),
            ],
            options={
                "db_table": "dev_stack",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[("PR", "Project"), ("ST", "Study")], max_length=2
                    ),
                ),
                (
                    "meet_type",
                    models.CharField(
                        choices=[("ON", "Online"), ("OF", "Offline")], max_length=2
                    ),
                ),
                ("location_info", models.CharField(blank=True, max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="")),
            ],
            options={
                "db_table": "post",
            },
        ),
    ]
